# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  xor_encryption_config = debug
  xor_decryption_config = debug

else ifeq ($(config),release)
  xor_encryption_config = release
  xor_decryption_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := xor_encryption xor_decryption

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

xor_encryption:
ifneq (,$(xor_encryption_config))
	@echo "==== Building xor_encryption ($(xor_encryption_config)) ===="
	@${MAKE} --no-print-directory -C xor_encryption -f Makefile config=$(xor_encryption_config)
endif

xor_decryption:
ifneq (,$(xor_decryption_config))
	@echo "==== Building xor_decryption ($(xor_decryption_config)) ===="
	@${MAKE} --no-print-directory -C xor_decryption -f Makefile config=$(xor_decryption_config)
endif

clean:
	@${MAKE} --no-print-directory -C xor_encryption -f Makefile clean
	@${MAKE} --no-print-directory -C xor_decryption -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   xor_encryption"
	@echo "   xor_decryption"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"